### ISSUE TITLE
Improve constituency page

### ISSUE THREAD

**Issue by colmdoyle** [colmdoyle/pobal#25]
We can probably make this page a little more useful.

Especially the current/former members boxes.

![screen shot 2016-03-01 at 18 08 05](https://cloud.githubusercontent.com/assets/406463/13436761/a5a8edd8-dfd8-11e5-89bb-2939aefdd87c.png)

**Comment by Beibhin** [comment]
Hi Colm,

I used the WhoismyTD.com website after seeing it in [Tang restaurant's climate action campaign](https://www.tang.ie/climateaction?fbclid=IwAR2zkiPZ_YGpp8fKiiRoUEXEDjc6nfEjcxbURpZc4lwbKCvIOz4ES0U0ZA0) info. It indicated I'm in the **Dublin NW** constituency. Based on that, I wrote to the three T.D.s for that constituency, but one of them (Ms Roisin Shortall) forwarded my email to a T.D. for **Dublin Central**, because she determined that's in fact the constituency I'm in.  I subsequently learned about the following Viewer which I believe is maintained by OSI, according to which I am in fact in the **Dublin Central** constituency. 

I really appreciate your creating a website to help people to find out who represents them. It would be great if you could resolve this issue I ran into. My address is 25 Valentia Rd, Drumcondra. I figure you'll need that for trouble-shooting. 

And let me know if I can help. I have a background in GIS (worked for twenty years in GIS for a water agency in the US) and just recently moved back to Ireland to live.

[Constituency_Boundaries_2017](https://www.arcgis.com/home/webmap/viewer.html?url=https://services6.arcgis.com/uWTLlTypaM5QTKd2/ArcGIS/rest/services/Constituency_Boundaries_2017/FeatureServer/3&source=sd)

Sincerely,

Angela
085 181 5472
